# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combined',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe', models.IntegerField(db_column='recipe', unique=True)),
                ('scores', models.BinaryField(db_column='scores')),
            ],
            options={
                'db_table': 'combined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ratings', models.BinaryField(blank=True, null=True)),
                ('times', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
    ]
